# Sets the symbol to "â¯" 
[character]
format = "[â¯](bold green) "
success_symbol = "[â¯](bold green) "
error_symbol = "[â¯](bold red) "

[package]
disabled = false

# Disable the AWS module.
[aws]
disabled = true

# Disable the GCP module.
[gcloud]
disabled = true

# Set the time format
[time]
disabled = false
time_format = "ğŸ“… %m/%d â±ï¸ %H:%M"
format = "[$time ](white bold)"

# Directory setttings
[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 3
read_only = " ğŸ”’"
truncate_to_repo = false
truncation_symbol = "â€¦/"

[username]
disabled = false
format = "[$user](bold yellow)[@](bold cyan)"
show_always = true

[hostname]
ssh_only = false
format = "[$hostname](bold red) "

[cmd_duration]
disabled = false
min_time = 500
format = "took [$duration](bold yellow) "

[git_status]
disabled = false
